[connections.mysql]
dialect = "mysql"
host = "172.17.0.2"
port = 3306
database = "test"
username = "root"
password = "root"


#[connections.mysql]
#dialect = "mysql"
#host = "172.17.0.2"
#port = 3306
#database = "pets"
#username = "root"
#password = "root"